#[derive(Debug, Clone, Default)]
pub struct MemorySnapshot {
    pub player_name: String,
    pub player_guid: Option<u64>,
    pub player_current_health: Option<u32>,
    pub player_max_health: Option<u32>,
    pub player_race: Option<u8>,
    pub player_level: Option<u32>,
    pub player_faction: Option<u32>,
    pub position: Option<(f32, f32, f32)>,
    pub heading_rad: Option<f32>,
    pub target_guid: Option<u64>,
    pub target_name: Option<String>,
    pub target_current_health: Option<u32>,
    pub target_max_health: Option<u32>,
    pub target_race: Option<u8>,
    pub target_level: Option<u32>,
    pub target_faction: Option<u32>,
    pub target_hostility: Option<String>,
    pub target_distance: Option<f32>,
    pub diagnostics: Vec<String>,
}
