#[derive(Debug, Clone, Copy)]
pub struct OffsetTable {
    pub client_connection_addr: usize,
    pub object_manager_offset: usize,
    pub local_guid_offset: usize,
    pub player_id_addr: usize,
    pub active_player_offset: usize,
    pub first_object_offset: usize,
    pub next_object_offset: usize,
    pub object_type_offset: usize,
    pub object_guid_offset: usize,
    pub object_storage_ptr_offset: usize,
    pub player_xyz_offset: usize,
    pub player_heading_offset: usize,
    pub unit_field_bytes0_offset: usize,
    pub unit_field_level_offset: usize,
    pub unit_field_faction_template_offset: usize,
    pub unit_field_flags_offset: usize,
    pub unit_field_display_id_offset: Option<usize>,
    pub unit_field_native_display_id_offset: Option<usize>,
    pub player_current_health_offset: Option<usize>,
    pub player_max_health_offset: Option<usize>,
    pub target_guid_addr: usize,
    pub target_current_health_offset: Option<usize>,
    pub target_max_health_offset: Option<usize>,
    pub player_names_store_addr: usize,
    pub player_names_first_node_offset: usize,
    pub player_names_next_offset: usize,
    pub player_names_guid_offset_primary: usize,
    pub player_names_name_offset: usize,
    pub monster_definition_offset: usize,
    pub unit_name_second_offset: usize,
    pub faction_sub_addr: usize,
    pub faction_base_addr: usize,
    pub faction_off1_offset: usize,
    pub faction_off2_offset: usize,
}

pub const WOTLK_3_3_5A: OffsetTable = OffsetTable {
    client_connection_addr: 0x00C79CE0,
    object_manager_offset: 0x2ED0,
    local_guid_offset: 0xC0,
    player_id_addr: 0x00CA1238,
    active_player_offset: 0x18,
    first_object_offset: 0xAC,
    next_object_offset: 0x3C,
    object_type_offset: 0x14,
    object_guid_offset: 0x30,
    object_storage_ptr_offset: 0x8,
    player_xyz_offset: 0x0798,
    player_heading_offset: 0x07A8,
    unit_field_bytes0_offset: 0x5C,
    unit_field_level_offset: 0xD8,
    unit_field_faction_template_offset: 0xDC,
    unit_field_flags_offset: 0xEC,
    unit_field_display_id_offset: None,
    unit_field_native_display_id_offset: None,
    player_current_health_offset: Some(0x60),
    player_max_health_offset: Some(0x80),
    target_guid_addr: 0x00BD07B0,
    target_current_health_offset: Some(0x60),
    target_max_health_offset: Some(0x80),
    player_names_store_addr: 0x00C5D938,
    player_names_first_node_offset: 0x1C,
    player_names_next_offset: 0x0C,
    player_names_guid_offset_primary: 0x10,
    player_names_name_offset: 0x20,
    monster_definition_offset: 0x964,
    unit_name_second_offset: 0x05C,
    faction_sub_addr: 0x00A47DD8,
    faction_base_addr: 0x00A47DCC,
    faction_off1_offset: 0xD4,
    faction_off2_offset: 0x0,
};
